name: Update GitHub Stats
on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api?username=Blaziod&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=dracula&locale=en&hide_border=false&order=1" \
            --output stats.svg

          curl -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            "https://github-readme-stats.vercel.app/api/top-langs?username=Blaziod&locale=en&hide_title=false&layout=compact&card_width=320&langs_count=5&theme=dracula&order=2" \
            --output top-langs.svg

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add stats.svg top-langs.svg
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
